const usersData = [
    {
      id: 1,
      name: "Conrad Alexander",
      teacherId: "10001",
      department: "Finance",
      students: 20,
      status: "Active",
    },
    {
      id: 2,
      name: "Marcelo Cruz",
      teacherId: "10002",
      department: "Engineer",
      students: 20,
      status: "Inactive",
    },
    {
      id: 3,
      name: "Bing Manalo",
      teacherId: "10003",
      department: "Arts",
      students: 16,
      status: "Blocked",
    },
    {
      id: 4,
      name: "Abby Andrews",
      teacherId: "10004",
      department: "Finance",
      students: 10,
      status: "Active",
    },
    {
      id: 5,
      name: "Conrad Alexander",
      teacherId: "10005",
      department: "Finance",
      students: 20,
      status: "Active",
    },
    {
      id: 6,
      name: "Marcelo Cruz",
      teacherId: "10006",
      department: "Arts",
      students: 20,
      status: "Suspended",
    },
    {
      id: 7,
      name: "Bing Manalo",
      teacherId: "10007",
      department: "Arts",
      students: 16,
      status: "Active",
    },
    {
      id: 8,
      name: "Abby Andrews",
      teacherId: "10008",
      department: "Finance",
      students: 10,
      status: "Active",
    },
    {
      id: 9,
      name: "Conrad Alexander",
      teacherId: "10009",
      department: "Engineer",
      students: 20,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Marcelo Cruz",
      teacherId: "10010",
      department: "Arts",
      students: 20,
      status: "Inactive",
    },
    {
      id: 11,
      name: "Conrad Alexander",
      teacherId: "10001",
      department: "Finance",
      students: 20,
      status: "Active",
    },
    {
      id: 12,
      name: "Marcelo Cruz",
      teacherId: "10002",
      department: "Engineer",
      students: 20,
      status: "Inactive",
    },
    {
      id: 13,
      name: "Bing Manalo",
      teacherId: "10003",
      department: "Arts",
      students: 16,
      status: "Blocked",
    },
    {
      id: 14,
      name: "Abby Andrews",
      teacherId: "10004",
      department: "Finance",
      students: 10,
      status: "Active",
    },
    {
      id: 15,
      name: "Conrad Alexander",
      teacherId: "10005",
      department: "Finance",
      students: 20,
      status: "Active",
    },
  ];


export default usersData;